from core.runtime_env import APP_ROOT, DATA_ROOT, SHARED_ROOT, MODELS_ROOT
DATA_DIR=SHARED_ROOT/'data'
PROJECTS_DIR=SHARED_ROOT/'projects'
ARTIFACTS_DIR=SHARED_ROOT/'artifacts'
UPLOADS_DIR=SHARED_ROOT/'uploads'
THUMBNAILS_DIR=SHARED_ROOT/'thumbnails'
CACHE_DIR=SHARED_ROOT/'cache'
LOGS_DIR=SHARED_ROOT/'logs'
CONFIG_DIR=SHARED_ROOT/'config'
for p in (DATA_DIR,PROJECTS_DIR,ARTIFACTS_DIR,UPLOADS_DIR,THUMBNAILS_DIR,CACHE_DIR,LOGS_DIR,CONFIG_DIR):p.mkdir(parents=True,exist_ok=True)
DB=DATA_DIR/'sdxl_studio.sqlite3'
MODELS_CONFIG=CONFIG_DIR/'models.json'
